name: "Sync Harvest to Tempo"

on:
  workflow_dispatch:

jobs:
  run-sync:
    name: "Run Sync"

    runs-on: ${{ matrix.operating-system }}

    strategy:
      matrix:
        dependencies:
          - "locked"
        php-version:
          - "8.3"
        operating-system:
          - "ubuntu-latest"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v5"
        with:
          fetch-depth: 0

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ matrix.php-version }}"
          ini-values: memory_limit=-1
          tools: composer:v2

      - name: "Cache dependencies"
        uses: "actions/cache@v4"
        with:
          path: |
            ~/.composer/cache
            vendor
          key: "php-${{ matrix.php-version }}-${{ matrix.dependencies }}"
          restore-keys: "php-${{ matrix.php-version }}-${{ matrix.dependencies }}"

      - name: "Install lowest dependencies"
        if: ${{ matrix.dependencies == 'lowest' }}
        run: "composer update --prefer-lowest --no-interaction --no-progress --no-suggest"

      - name: "Install highest dependencies"
        if: ${{ matrix.dependencies == 'highest' }}
        run: "composer update --no-interaction --no-progress --no-suggest"

      - name: "Install locked dependencies"
        if: ${{ matrix.dependencies == 'locked' }}
        run: "composer install --no-interaction --no-progress --no-suggest"

      - name: "Run sync on everything"
        run: "bin/sync-everything.php"
        env:
          "FALLBACK_JIRA_ISSUE_INTERNAL_ID": ${{ secrets.FALLBACK_JIRA_ISSUE_INTERNAL_ID }}
          "FALLBACK_JIRA_ISSUE_ID": ${{ secrets.FALLBACK_JIRA_ISSUE_ID }}
          "TEMPO_ACCESS_TOKEN": ${{ secrets.TEMPO_ACCESS_TOKEN }}
          "JIRA_ACCOUNT_ID": ${{ secrets.JIRA_ACCOUNT_ID }}
          "JIRA_ACCOUNT_EMAIL": ${{ secrets.JIRA_ACCOUNT_EMAIL }}
          "JIRA_API_TOKEN": ${{ secrets.JIRA_API_TOKEN }}
          "JIRA_BASE_URL": ${{ secrets.JIRA_BASE_URL }}
          "HARVEST_ACCOUNT_ID": ${{ secrets.HARVEST_ACCOUNT_ID }}
          "HARVEST_ACCESS_TOKEN": ${{ secrets.HARVEST_ACCESS_TOKEN }}
          "HARVEST_PROJECT_ID": ${{ secrets.HARVEST_PROJECT_ID }}
          "TEMPO_CUSTOM_WORKLOG_ATTRIBUTES": ${{ secrets.TEMPO_CUSTOM_WORKLOG_ATTRIBUTES }}
